# Generated by Django 5.0.6 on 2026-06-16 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('position_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'workflow_state',
                'ordering': ['position_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_definition',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('requires_approval', models.BooleanField(default=False)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflows.state')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflows.state')),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_transition',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='state',
            name='workflow_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflows.workflowdefinition'),
        ),
        migrations.AddConstraint(
            model_name='transition',
            constraint=models.UniqueConstraint(fields=('workflow_definition', 'from_state', 'to_state', 'name'), name='unique_transition_per_path'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('workflow_definition', 'name'), name='unique_state_name_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('workflow_definition', 'position_order'), name='unique_state_order_per_workflow'),
        ),
    ]
