# Generated by Django 5.0.6 on 2026-06-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='requires_task',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='state',
            name='task_assigned_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='state',
            name='task_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='task_sla_hours',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddField(
            model_name='state',
            name='task_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
