# Generated by Django 5.0.6 on 2026-06-16 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_state_requires_task_state_task_assigned_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.JSONField(default=dict)),
                ('action', models.JSONField(default=dict)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='workflows.transition')),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_rule',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
