# Generated by Django 5.0.6 on 2026-06-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_rule'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transition',
            name='unique_transition_per_path',
        ),
        migrations.RemoveField(
            model_name='state',
            name='requires_task',
        ),
        migrations.RemoveField(
            model_name='state',
            name='task_assigned_role',
        ),
        migrations.RemoveField(
            model_name='state',
            name='task_description',
        ),
        migrations.RemoveField(
            model_name='state',
            name='task_sla_hours',
        ),
        migrations.RemoveField(
            model_name='state',
            name='task_title',
        ),
        migrations.AddField(
            model_name='state',
            name='sla_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='state',
            name='task_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transition',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='reference_prefix',
            field=models.CharField(default='WFF', max_length=10),
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='transition',
            constraint=models.UniqueConstraint(fields=('from_state', 'to_state'), name='unique_transition_per_path'),
        ),
    ]
