# Generated by Django 5.0.6 on 2026-06-22 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_remove_transition_unique_transition_per_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdefinition',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='workflows.workflowdefinition'),
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
