# Generated by Django 5.0.6 on 2026-07-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_workflowdefinition_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdefinition',
            name='ui_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
