# Generated by Django 5.0.6 on 2026-07-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_workflowdefinition_ui_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='canvas_position',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
