# Generated by Django 5.0.6 on 2026-07-04 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('workflows', '0005_workflowdefinition_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='event_trigger',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('events', models.JSONField(blank=True, default=list)),
                ('secret', models.CharField(blank=True, help_text='Used to HMAC-SHA256 sign payloads (X-FlowForge-Signature)', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('workflow_definition', models.ForeignKey(blank=True, help_text='Blank = fires for every workflow', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'webhook_subscription',
                'ordering': ['-created_at'],
            },
        ),
    ]
