# Generated by Django 5.0.6 on 2026-07-18 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0004_workflowinstance_child_order_workflowinstance_parent'),
        ('notifications', '0002_notificationlog_event_trigger_webhooksubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_trigger', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('delivered', 'Delivered'), ('failed', 'Failed (Retrying)'), ('dead_letter', 'Dead Letter (Max Retries Exceeded)')], default='queued', max_length=20)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('http_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.webhooksubscription')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_delivery_logs', to='instances.workflowinstance')),
            ],
            options={
                'db_table': 'webhook_delivery_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='webhook_del_status_a0ac57_idx'), models.Index(fields=['webhook_subscription', '-created_at'], name='webhook_del_webhook_1cb732_idx')],
            },
        ),
    ]
