# Generated by Django 5.0.6 on 2026-07-25 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0005_trigger'),
        ('notifications', '0003_webhookdeliverylog'),
        ('workflows', '0007_state_canvas_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionHook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('before', 'Before (gates the transition)'), ('after', 'After (fires once committed)')], default='after', max_length=10)),
                ('action', models.CharField(choices=[('http_request', 'HTTP request'), ('probe', 'Probe (GET, assert reachable)')], default='http_request', max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('on_failure', models.CharField(choices=[('block', 'Block the transition'), ('warn', 'Warn but proceed'), ('ignore', 'Ignore')], default='warn', max_length=10)),
                ('output_to', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hooks', to=settings.AUTH_USER_MODEL)),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='workflows.transition')),
            ],
            options={
                'db_table': 'transition_hook',
                'ordering': ['transition_id', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HookExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('succeeded', 'Succeeded'), ('failed', 'Failed (Retrying)'), ('dead_letter', 'Dead Letter')], default='queued', max_length=20)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('http_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('request_summary', models.TextField(blank=True)),
                ('response_summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hook_executions', to='instances.workflowinstance')),
                ('hook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='notifications.transitionhook')),
            ],
            options={
                'db_table': 'hook_execution_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
