# Generated by Django 5.0.6 on 2026-06-16 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('instance_created', 'Instance Created'), ('transition', 'Transition'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('form_submitted', 'Form Submitted'), ('rule_fired', 'Rule Fired')], max_length=40)),
                ('from_state', models.CharField(blank=True, max_length=100)),
                ('to_state', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='instances.workflowinstance')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['created_at'],
            },
        ),
    ]
