# Generated by Django 5.0.6 on 2026-06-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('instance_created', 'Instance Created'), ('transition', 'Transition'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('form_submitted', 'Form Submitted'), ('rule_fired', 'Rule Fired'), ('comment', 'Comment')], max_length=40),
        ),
    ]
