# Generated by Django 5.0.6 on 2026-07-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('instance_created', 'Instance Created'), ('transition', 'Transition'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('form_submitted', 'Form Submitted'), ('rule_fired', 'Rule Fired'), ('comment', 'Comment'), ('metadata_updated', 'Metadata Updated'), ('relationship_added', 'Relationship Added'), ('relationship_removed', 'Relationship Removed'), ('sla_breached', 'SLA Breached'), ('child_added', 'Child Instance Added'), ('child_moved', 'Child Instance Moved')], max_length=40),
        ),
    ]
