# Generated by Django 5.0.6 on 2026-07-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='form_definition_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
