# Generated by Django 5.0.6 on 2026-07-05 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='FlowForge', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Workflow Automation', max_length=150)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('ui_config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspace',
            },
        ),
    ]
