"""Roles become data (docs/ROLES.md step 1).

Deliberately inert: this adds the shape and backfills the five built-in roles
so that `require_capability` can be built on it next. Nothing reads the new
fields yet, and `name` is kept equal to `key` because every permission check
still compares against `name`. Letting those diverge would silently stop
checks matching, which is the worst failure mode a permissions change has.

Written by hand rather than autogenerated because `key` is unique: it has to
be added nullable, backfilled, then tightened, and no single default works.
"""
import django.db.models.deletion
from django.db import migrations, models


def backfill_roles(apps, schema_editor):
    """Give existing rows a key, and stamp the built-ins with their config."""
    Role = apps.get_model("accounts", "Role")

    # Imported rather than duplicated so the migration cannot drift from the
    # model's definition of what each built-in role may do.
    from apps.accounts.models import SYSTEM_ROLES

    for role in Role.objects.all():
        role.key = role.name
        spec = SYSTEM_ROLES.get(role.name)
        if spec:
            role.label = spec["label"]
            role.capabilities = spec["capabilities"]
            role.rank = spec["rank"]
            role.is_system = True
        else:
            # A row outside the built-in five: keep it, but grant nothing.
            # Silently inventing permissions for an unknown role would be a
            # privilege escalation dressed as a migration.
            role.label = role.name.replace("_", " ").title()
            role.capabilities = []
        role.save()

    # Deliberately does NOT create missing roles. Seeding the built-in five
    # here would put them in every freshly-migrated database — including every
    # test database — and the existing `Role.objects.create(name=...)` calls
    # across the suite would then collide on the unique name. Roles are still
    # created by `seed` and by tests, exactly as before; this migration only
    # gives rows that already exist their new shape.


def unbackfill(apps, schema_editor):
    """Reverse leaves the rows alone — only the added columns go away."""


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_workspace")]

    operations = [
        # 1. Add the new columns, `key` nullable so existing rows survive.
        migrations.AddField(
            model_name="role",
            name="key",
            field=models.SlugField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="role",
            name="label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="role",
            name="capabilities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="role",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="rank",
            field=models.PositiveIntegerField(default=0),
        ),
        # 2. Backfill before the unique constraint can bite.
        migrations.RunPython(backfill_roles, unbackfill),
        # 3. Tighten to the model's definition.
        migrations.AlterField(
            model_name="role",
            name="key",
            field=models.SlugField(max_length=50, unique=True),
        ),
        # `name` loses its choices: roles are data now, so the enum can no
        # longer be the source of valid values.
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
