# Generated by Django 5.0.6 on 2026-06-16 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_instances', to=settings.AUTH_USER_MODEL)),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.state')),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_instance',
                'ordering': ['-created_at'],
            },
        ),
    ]
