# Generated by Django 5.0.6 on 2026-06-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowinstance',
            old_name='metadata',
            new_name='metadata_json',
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
