# Generated by Django 5.0.6 on 2026-06-22 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0002_rename_metadata_workflowinstance_metadata_json_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rel_type', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relationships', to=settings.AUTH_USER_MODEL)),
                ('from_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='instances.workflowinstance')),
                ('to_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='instances.workflowinstance')),
            ],
            options={
                'db_table': 'instance_relationship',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='instancerelationship',
            constraint=models.UniqueConstraint(fields=('from_instance', 'to_instance', 'rel_type'), name='unique_relationship'),
        ),
    ]
