# Generated by Django 5.0.6 on 2026-07-13 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0003_instancerelationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='child_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='instances.workflowinstance'),
        ),
    ]
