# Generated by Django 5.0.6 on 2026-07-25 06:38

import apps.instances.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0004_workflowinstance_child_order_workflowinstance_parent'),
        ('workflows', '0007_state_canvas_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('token', models.CharField(default=apps.instances.models.generate_trigger_token, editable=False, max_length=64, unique=True)),
                ('action', models.CharField(choices=[('create_instance', 'Create instance'), ('fire_transition', 'Fire transition')], max_length=20)),
                ('lookup_field', models.CharField(blank=True, default='reference_number', max_length=100)),
                ('metadata_mapping', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_triggers', to=settings.AUTH_USER_MODEL)),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='workflows.transition')),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'trigger',
                'ordering': ['-created_at'],
            },
        ),
    ]
